config/routes.rb
CatTest::Application.routes.draw do
  resources :kitties

  root 'kitties#sell_index'
  get 'share_count' => 'kitties#sell_count'

  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/kitty.rb
class Kitty < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController
  before_action :set_kitty, only: [:show, :edit, :update, :destroy]

  # GET /kitties
  # GET /kitties.json
  def index
    @kitties = Kitty.all
  end

  # GET /kitties/1
  # GET /kitties/1.json
  def show
  end

  # GET /kitties/new
  def new
    @kitty = Kitty.new
  end

  # GET /kitties/1/edit
  def edit
  end

  # POST /kitties
  # POST /kitties.json
  def create
    @kitty = Kitty.new(kitty_params)

    respond_to do |format|
      if @kitty.save
        format.html { redirect_to @kitty, notice: 'Kitty was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kitty }
      else
        format.html { render action: 'new' }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitties/1
  # PATCH/PUT /kitties/1.json
  def update
    respond_to do |format|
      if @kitty.update(kitty_params)
        format.html { redirect_to @kitty, notice: 'Kitty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitties/1
  # DELETE /kitties/1.json
  def destroy
    @kitty.destroy
    respond_to do |format|
      format.html { redirect_to kitties_url }
      format.json { head :no_content }
    end
  end

  def sell_index
    
  end

  def sell_count
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitty
      @kitty = Kitty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitty_params
      params[:kitty]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitties_helper.rb
module KittiesHelper
end

app/views/kitties/_form.html.erb
<%= form_for(@kitty) do |f| %>
  <% if @kitty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitty.errors.count, "error") %> prohibited this kitty from being saved:</h2>

      <ul>
      <% @kitty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitties/edit.html.erb
<h1>Editing kitty</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitty %> |
<%= link_to 'Back', kitties_path %>

app/views/kitties/index.html.erb
<h1>Listing kitties</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @kitties.each do |kitty| %>
      <tr>
        <td><%= link_to 'Show', kitty %></td>
        <td><%= link_to 'Edit', edit_kitty_path(kitty) %></td>
        <td><%= link_to 'Destroy', kitty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitty', new_kitty_path %>

app/views/kitties/new.html.erb
<h1>New kitty</h1>

<%= render 'form' %>

<%= link_to 'Back', kitties_path %>

app/views/kitties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kitty_path(@kitty) %> |
<%= link_to 'Back', kitties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>